# Site
repository: gagankukkar/gagankukkar.github.io
favicon: images/sunglasses.png

# Content configuration version
version: 2

# Personal info
name: Gagan Kukkar
title: Problem Solver + Leader
# email: jekyll@email.co.uk
# website: www.github.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyll
github_username:  gagankukkar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: gkukkar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my site! I'm a detail-oriented problem solver and natural born leader with 5+ years professional experience in a variety of industries. 

  My background in engineering has given me the ability to absorb new information efficiently and analyze problems in a creative way.

  I've mastered my ability to work effectively in a team, as well as communicate with technical and non-technical audiences alike. 

  Looking for an opportunity where I can take advantage of my soft and hard skills to provide value to a meaningful organization.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Waterloo
        caption: 2014 - 2019
        sub_title: BASc Mechanical Engineering
        quote: >
          In 1957, Waterloo opened its doors to 74 engineering students with co-operative education as its cornerstone. Today, with more than 42,000+ students attending annually, Waterloo is #1 in Canada for experiential learning and employer-student connections.
        description: | # this will include new lines to allow paragraphs
          During my time at Waterloo I learned many key skills that I have taken with me through my career such as teamwork and working with tight deadlines. I thoroughly enjoyed my time at university and learned a lot about a healthy work-life balance.

          I had the opportunity to gain professional work experience while in school through the co-op program which strengthened my education.

          I spent a lot of my free time as the *Mechanical Engineering Class Rep* to ensure successful student-professor relations.
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bitaccess
        link: bitaccess.ca
        # link_text: bitaccess.ca
        sub_title: Software Support Engineer
        caption: 2021 - 2022
        quote: >
          From start-ups to Fortune 500 companies, Bitaccess provides software services to power Fintech businesses in over 15 countries. Bitaccess is the world's leading vendor of Bitcoin ATMs (BTM).
        description: | # this will include new lines to allow paragraphs
            I served as the liaison between the Support team and Engineering teams. I investigated technical issues reported by customers to resolve them as soon as possible. I also took ownership of the software used by the Support team to manage customer and product data. As a result, I had the opportunity to work with a variety of individuals to drive excellent customer experience while developing high-quality software for better internal productivity.
  
      - layout: left
        title: TE Connectivity
        link: te.com
        # link_text: te.com
        sub_title: Product Development Engineer
        caption: 2019 - 2021
        quote: >
          For more than 75 years, TE Connectivity has partnered with customers to produce highly engineered connectivity and sensing products that make a connected world possible.
        description: | # this will include new lines to allow paragraphs
            As part of the Energy business unit, I performed mechanical and electrical testing of high-voltage  connector samples to maximize product quality. I led a new capital project to successfully progress it from its initial phase to prototyping phase in the product's development life cycle. Lastly, I explored and implemented new technologies to provide cost-savings related to the inspection of production samples.
  
  - title: Software Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          <mark>This section is still in progress. Feel free to look at my Github profile in the meantime. Thank you for your patience! 😎</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Spending time with family and friends
      - Playing with my cat
      - Exercise/gym/sports

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
